# Generated by Django 2.1.3 on 2018-12-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_auto_20181218_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('qq', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.User')),
            ],
        ),
    ]
